#!/usr/bin/env bash
# This script gives information about the school file

file_name="school"

# check if the file exists
if [ -e $file_name ]
then
	echo "school file exists"

	# Check if the file is empty
	if [ -s $file_name ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	# Check if the file is a regular file
	if [ -f $file_name ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
