#!/usr/bin/env bash
# Configures an Ubuntu server
cp /etc/hosts ~/hosts.new

# Modify localhost entry in the copied hosts file
sed -i 's/^127\.0\.0\.1\s\+localhost/127.0.0.2\tlocalhost/' ~/hosts.new

# Ensure facebook.com resolves to 8.8.8.8 in the copied hosts file
if ! grep -q '^8.8.8.8\s\+facebook.com' ~/hosts.new;
then
  echo "8.8.8.8 facebook.com" >> ~/hosts.new
fi

# Replace the original /etc/hosts with the modified file
cp -f ~/hosts.new /etc/hosts
