#!/usr/bin/env bash
# Configures an Ubuntu server
cp /etc/hosts ~/hosts.new
sed 's/^127\.0\.0\.1\tlocalhost/127\.0\.0\.2\slocalhost/' /etc/hosts.new
grep '.+facebook.com' || echo "8.8.8.8 facebook.com" >> /etc/hosts.new
cp -f ~/hosts.new /etc/hosts
